scp: Avoid "output may be truncated" warning
The warning is spurious since the buffer size is checked prior to
snprintf.  The warning seems to only occur with -O2, not -Os.
No functional change.

src/scp.c:1031:56: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 2 and 4095 [-Werror=format-truncation=]